# Generated by Django 2.2 on 2019-11-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=False)),
                ('board', models.CharField(default=False, max_length=20)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=30)),
                ('schoolName', models.CharField(max_length=30)),
                ('schoolAddress', models.CharField(max_length=200)),
                ('homeAddress', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
                ('aadharNumber', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('emailID', models.EmailField(max_length=40)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('referral', models.CharField(max_length=254)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.CharField(max_length=254)),
            ],
        ),
    ]
