# Generated by Django 2.2 on 2019-11-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhim_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(max_length=64)),
                ('phoneNumber', models.CharField(max_length=64)),
            ],
        ),
    ]
