# Generated by Django 2.2 on 2019-11-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best', '0004_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformclass',
            name='date',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
