# Generated by Django 2.2 on 2019-12-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best', '0005_applicationformclass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformclass',
            name='mail_sent',
            field=models.CharField(default='no', max_length=64),
        ),
    ]
